### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/prep-portfolio-22.NOV.PREP.2#21]
README instructions are not sufficient for seamless installation/setup

**Comment by pixawna** [comment]
Would love to work on this issue.

**Comment by IvyJeptoo** [comment]
> Would love to work on this issue.

I had added some info to the readme but feel free to go through it also and make changes

**Comment by grace-omotoso** [comment]
Ivy worked on it.
