### ISSUE TITLE
Create a logo for the Pod Portfolio

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/prep-portfolio-22.NOV.PREP.2#27]
Besides the MLH Logo, it will be great if we can come up with a logo that goes with our pod mascot on the pod portfolio.

**Comment by kph4m** [comment]
I can try!

**Comment by pixawna** [comment]
I want to work on the same

**Comment by pixawna** [comment]
![logo](https://user-images.githubusercontent.com/81790585/201159980-84a7e100-555f-4d00-bc87-af830d270339.png)
Can you please check and let me know the changes so that I can create PR with the same

**Comment by kph4m** [comment]
![image](https://user-images.githubusercontent.com/76819117/201439948-a6da5541-4c92-4ee1-b171-94ca0b06c250.png)
let me know what you think!

**Comment by grace-omotoso** [comment]
@kpham841 @Bhawna1203 I am waiting to see the hybrid of these two logos. Please sync up to get it done

**Comment by Bhawna1203** [comment]
![logo](https://user-images.githubusercontent.com/81790585/201384984-65b02ab4-9a0f-4788-aa8b-1571a62f73c6.png)
Is it good mam?

**Comment by pixawna** [comment]
![logo](https://user-images.githubusercontent.com/81790585/201385553-bae6a8e2-3897-4047-9bf4-bf4dec29e61b.png)
Mam is it looking good?
Than i will create the pr for the same

**Comment by ShivamTyagi12345** [comment]
![Logo](https://user-images.githubusercontent.com/60812924/201433474-a851b2a3-69e0-431a-8dd4-95cd6db20d78.png)

**Comment by indevi** [comment]
![Simple Badger Head Mascot Sports Circle Logo](https://user-images.githubusercontent.com/60812924/201435301-ba57fd71-7176-47dc-ab63-021256e7e1ff.png)

**Comment by indevi** [comment]
![Simple Badger Head Mascot Sports Circle Logo (1)](https://user-images.githubusercontent.com/60812924/201441374-77c3eb94-e74c-43d3-be66-5a676da2294d.png)
