### ISSUE TITLE
Add pod stats

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.NOV.PREP.2#4]
Add a way to display the number of contributions between fellows. Make a little leaderboard or similar to motivate people to add new issues!

**Comment by norachams** [comment]
group 1 is doing this

**Comment by youngjun827** [comment]
Mindmap:
1. Utilize Github API to query the repository:
https://api.github.com/repos/MLH-Fellowship/prep-portfolio-22.NOV.PREP.2/contributors
2. Sort the list of contributors in descending order.
3. We are done!
