### ISSUE TITLE
Centering and favicon

### ISSUE THREAD

**Issue by kph4m** [MLH-Fellowship/prep-portfolio-22.NOV.PREP.2#57]
Welcome message and projects section aren't centered. Change Byter Badgers to Byte Badgers in welcome message.
![image](https://user-images.githubusercontent.com/76819117/201729270-314a91f9-4fdb-431d-9c95-80924b60e83f.png)

![image](https://user-images.githubusercontent.com/76819117/201729360-6c77c6df-40bd-42df-b19e-8bd74a52bbe3.png)

Update favicon to our mascot logo
![image](https://user-images.githubusercontent.com/76819117/201729407-a421793b-f882-4234-bd1b-ae4b571965b2.png)

**Comment by IvyJeptoo** [comment]
working on it
