### ISSUE TITLE
Add a navigation bar

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.NOV.PREP.2#8]
As the portfolio gains more information, it may make sense to add a navigation bar. This bar should include the logo on the left side but only once the page has scrolled down a bit.

**Comment by carlykiang** [comment]
Group 2 would like to do this!

**Comment by ShivamTyagi12345** [comment]
Hey @carlykiang , Please add any other improvements you would like to 

![image](https://user-images.githubusercontent.com/60812924/200825835-33d9b23e-0bd7-486e-8dcd-59b60452a1d7.png)

![image](https://user-images.githubusercontent.com/60812924/200825962-016fd35b-05b4-4905-8e6d-b9564daac893.png)
